# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cobblenuutt"

[ejs.landing]
mediaGitHubURL = "https://nuutt-cobblemon.com"
mediaXURL = "https://x.com/Cobblenuutt"
mediaInstagramURL = "https://www.instagram.com/cobblenuutt?igsh=eHVjNzh5Ymp6bHNu&utm_source=qr"
mediaYouTubeURL = "https://www.tiktok.com/@cobblenuutt?_r=1&_t=ZN-91Mri1IcG6I"
mediaDiscordURL = "https://discord.gg/QndGWrM5r7"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO WESTEROSCRAFT"
welcomeDescription = "Our mission is to recreate the universe imagined by author George RR Martin in his fantasy series, A Song of Ice and Fire.  Through the collaborative effort of thousands of community members, we have sought to create Westeros as accurately and precisely as possible within Minecraft.  The world we are creating is yours to explore.  Journey from Dorne to Castle Black, and if you arenâ€™t afraid, beyond the Wall itself, but best not delay.  As the words of House Stark ominously warn: Winter is Coming."
welcomeDescCTA = "You are just a few clicks away from Westeros."
